/**
 * 
 */
package com.jf.scout.shared.ui.wizards;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class DatabaseSetupFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public DatabaseSetupFormData() {
  }

  /**
   * access method for property DatabaseSetupNr.
   */
  public Long getDatabaseSetupNr() {
    return getDatabaseSetupNrProperty().getValue();
  }

  /**
   * access method for property DatabaseSetupNr.
   */
  public void setDatabaseSetupNr(Long databaseSetupNr) {
    getDatabaseSetupNrProperty().setValue(databaseSetupNr);
  }

  public DatabaseSetupNrProperty getDatabaseSetupNrProperty() {
    return getPropertyByClass(DatabaseSetupNrProperty.class);
  }

  public static class DatabaseSetupNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public DatabaseSetupNrProperty() {
    }
  }
}
