/**
 * 
 */
package jfscout.shared.hrm.ui.forms;

import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class EmployeeListSearchFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public EmployeeListSearchFormData() {
  }

  public Code getCode() {
    return getFieldByClass(Code.class);
  }

  public FullName getFullName() {
    return getFieldByClass(FullName.class);
  }

  public HeadOfUnit getHeadOfUnit() {
    return getFieldByClass(HeadOfUnit.class);
  }

  public static class Code extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Code() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class FullName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public FullName() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class HeadOfUnit extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public HeadOfUnit() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }
}
