/**
 * 
 */
package jfscout.shared.administration.ui.forms;

import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class RoleFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public RoleFormData() {
  }

  public RoleName getRoleName() {
    return getFieldByClass(RoleName.class);
  }

  /**
   * access method for property RoleNr.
   */
  public Long getRoleNr() {
    return getRoleNrProperty().getValue();
  }

  /**
   * access method for property RoleNr.
   */
  public void setRoleNr(Long roleNr) {
    getRoleNrProperty().setValue(roleNr);
  }

  public RoleNrProperty getRoleNrProperty() {
    return getPropertyByClass(RoleNrProperty.class);
  }

  public Valid getValid() {
    return getFieldByClass(Valid.class);
  }

  public static class RoleName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public RoleName() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class RoleNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public RoleNrProperty() {
    }
  }

  public static class Valid extends AbstractValueFieldData<Boolean> {

    private static final long serialVersionUID = 1L;

    public Valid() {
    }
  }
}
