/**
 * 
 */
package com.jf.scout.shared.administration.ui.desktop.pages;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PermissionManagementTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public PermissionManagementTablePageData() {
  }

  @Override
  public PermissionManagementTableRowData addRow() {
    return (PermissionManagementTableRowData) super.addRow();
  }

  @Override
  public PermissionManagementTableRowData addRow(int rowState) {
    return (PermissionManagementTableRowData) super.addRow(rowState);
  }

  @Override
  public PermissionManagementTableRowData createRow() {
    return new PermissionManagementTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return PermissionManagementTableRowData.class;
  }

  @Override
  public PermissionManagementTableRowData[] getRows() {
    return (PermissionManagementTableRowData[]) super.getRows();
  }

  @Override
  public PermissionManagementTableRowData rowAt(int index) {
    return (PermissionManagementTableRowData) super.rowAt(index);
  }

  public void setRows(PermissionManagementTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class PermissionManagementTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String permissionName = "permissionName";
    public static final String description = "description";
    private String m_permissionName;
    private String m_description;

    public PermissionManagementTableRowData() {
    }

    /**
     * @return the PermissionName
     */
    public String getPermissionName() {
      return m_permissionName;
    }

    /**
     * @param permissionName
     *          the PermissionName to set
     */
    public void setPermissionName(String permissionName) {
      m_permissionName = permissionName;
    }

    /**
     * @return the Description
     */
    public String getDescription() {
      return m_description;
    }

    /**
     * @param description
     *          the Description to set
     */
    public void setDescription(String description) {
      m_description = description;
    }
  }
}
