/**
 * 
 */
package com.jf.scout.shared.core.ui.desktop.forms;

import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class WelcomeFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public WelcomeFormData() {
  }

  public WelcomeMessage getWelcomeMessage() {
    return getFieldByClass(WelcomeMessage.class);
  }

  /**
   * access method for property WelcomeNr.
   */
  public Long getWelcomeNr() {
    return getWelcomeNrProperty().getValue();
  }

  /**
   * access method for property WelcomeNr.
   */
  public void setWelcomeNr(Long welcomeNr) {
    getWelcomeNrProperty().setValue(welcomeNr);
  }

  public WelcomeNrProperty getWelcomeNrProperty() {
    return getPropertyByClass(WelcomeNrProperty.class);
  }

  public static class WelcomeMessage extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public WelcomeMessage() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, Integer.MAX_VALUE);
    }
  }

  public static class WelcomeNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public WelcomeNrProperty() {
    }
  }
}
