/**
 * 
 */
package jfscout.shared.administration.ui.desktop.pages;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class RoleTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public RoleTablePageData() {
  }

  @Override
  public RoleTableRowData addRow() {
    return (RoleTableRowData) super.addRow();
  }

  @Override
  public RoleTableRowData addRow(int rowState) {
    return (RoleTableRowData) super.addRow(rowState);
  }

  @Override
  public RoleTableRowData createRow() {
    return new RoleTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return RoleTableRowData.class;
  }

  @Override
  public RoleTableRowData[] getRows() {
    return (RoleTableRowData[]) super.getRows();
  }

  @Override
  public RoleTableRowData rowAt(int index) {
    return (RoleTableRowData) super.rowAt(index);
  }

  public void setRows(RoleTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class RoleTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String roleId = "roleId";
    public static final String roleName = "roleName";
    public static final String valid = "valid";
    public static final String validChangeDate = "validChangeDate";
    public static final String status = "status";
    public static final String createdTime = "createdTime";
    public static final String creator = "creator";
    public static final String lastModifiedTime = "lastModifiedTime";
    public static final String lastModifier = "lastModifier";
    private Long m_roleId;
    private String m_roleName;
    private Boolean m_valid;
    private Date m_validChangeDate;
    private String m_status;
    private Date m_createdTime;
    private String m_creator;
    private Date m_lastModifiedTime;
    private String m_lastModifier;

    public RoleTableRowData() {
    }

    /**
     * @return the RoleId
     */
    public Long getRoleId() {
      return m_roleId;
    }

    /**
     * @param roleId
     *          the RoleId to set
     */
    public void setRoleId(Long roleId) {
      m_roleId = roleId;
    }

    /**
     * @return the RoleName
     */
    public String getRoleName() {
      return m_roleName;
    }

    /**
     * @param roleName
     *          the RoleName to set
     */
    public void setRoleName(String roleName) {
      m_roleName = roleName;
    }

    /**
     * @return the Valid
     */
    public Boolean getValid() {
      return m_valid;
    }

    /**
     * @param valid
     *          the Valid to set
     */
    public void setValid(Boolean valid) {
      m_valid = valid;
    }

    /**
     * @return the ValidChangeDate
     */
    public Date getValidChangeDate() {
      return m_validChangeDate;
    }

    /**
     * @param validChangeDate
     *          the ValidChangeDate to set
     */
    public void setValidChangeDate(Date validChangeDate) {
      m_validChangeDate = validChangeDate;
    }

    /**
     * @return the Status
     */
    public String getStatus() {
      return m_status;
    }

    /**
     * @param status
     *          the Status to set
     */
    public void setStatus(String status) {
      m_status = status;
    }

    /**
     * @return the CreatedTime
     */
    public Date getCreatedTime() {
      return m_createdTime;
    }

    /**
     * @param createdTime
     *          the CreatedTime to set
     */
    public void setCreatedTime(Date createdTime) {
      m_createdTime = createdTime;
    }

    /**
     * @return the Creator
     */
    public String getCreator() {
      return m_creator;
    }

    /**
     * @param creator
     *          the Creator to set
     */
    public void setCreator(String creator) {
      m_creator = creator;
    }

    /**
     * @return the LastModifiedTime
     */
    public Date getLastModifiedTime() {
      return m_lastModifiedTime;
    }

    /**
     * @param lastModifiedTime
     *          the LastModifiedTime to set
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
      m_lastModifiedTime = lastModifiedTime;
    }

    /**
     * @return the LastModifier
     */
    public String getLastModifier() {
      return m_lastModifier;
    }

    /**
     * @param lastModifier
     *          the LastModifier to set
     */
    public void setLastModifier(String lastModifier) {
      m_lastModifier = lastModifier;
    }
  }
}
