/**
 * 
 */
package jfscout.shared.hrm.ui.desktop.pages;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class EmployeeReportTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public EmployeeReportTablePageData() {
  }

  @Override
  public EmployeeReportTableRowData addRow() {
    return (EmployeeReportTableRowData) super.addRow();
  }

  @Override
  public EmployeeReportTableRowData addRow(int rowState) {
    return (EmployeeReportTableRowData) super.addRow(rowState);
  }

  @Override
  public EmployeeReportTableRowData createRow() {
    return new EmployeeReportTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return EmployeeReportTableRowData.class;
  }

  @Override
  public EmployeeReportTableRowData[] getRows() {
    return (EmployeeReportTableRowData[]) super.getRows();
  }

  @Override
  public EmployeeReportTableRowData rowAt(int index) {
    return (EmployeeReportTableRowData) super.rowAt(index);
  }

  public void setRows(EmployeeReportTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class EmployeeReportTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;

    public EmployeeReportTableRowData() {
    }
  }
}
