/**
 * 
 */
package jfscout.shared.hrm.ui.desktop.pages;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class EmployeeTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public EmployeeTablePageData() {
  }

  @Override
  public EmployeeTableRowData addRow() {
    return (EmployeeTableRowData) super.addRow();
  }

  @Override
  public EmployeeTableRowData addRow(int rowState) {
    return (EmployeeTableRowData) super.addRow(rowState);
  }

  @Override
  public EmployeeTableRowData createRow() {
    return new EmployeeTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return EmployeeTableRowData.class;
  }

  @Override
  public EmployeeTableRowData[] getRows() {
    return (EmployeeTableRowData[]) super.getRows();
  }

  @Override
  public EmployeeTableRowData rowAt(int index) {
    return (EmployeeTableRowData) super.rowAt(index);
  }

  public void setRows(EmployeeTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class EmployeeTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String id = "id";
    private Long m_id;

    public EmployeeTableRowData() {
    }

    /**
     * @return the Id
     */
    public Long getId() {
      return m_id;
    }

    /**
     * @param id
     *          the Id to set
     */
    public void setId(Long id) {
      m_id = id;
    }
  }
}
